### ISSUE TITLE
CS125的教科书

### ISSUE THREAD

**Issue by houkensjtu** [CoolPhilChen/SJTU-Courses#1]
感谢分享课程内容！想问这是软件学院现行的课程吗？看到参考书目中谭老师的名字不禁有点虚。。。在2019年选择c++语言教大一学生也有点震惊。

**Comment by CoolPhilChen** [comment]
不太清楚是不是软件学院现行的课程. 我们当时上的时候没有教科书, 就是PPT. 但这课已经年代久远了, 不知道现在变没变.

**Comment by houkensjtu** [comment]
谢谢！如果有同学可以更新一下最近的情况就好了。。希望学校没有再用这些过时的东西毒害学生了，我也有关注浙大的课程分享，那边的教学材料看上去现代化很多

**Comment by DiamondI** [comment]
这个issue有一段时间没有更新了，现在先暂时关闭本issue，将来如果有出现与本issue相关的问题，可以重新打开这个issue并进一步讨论。
