### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by 2286252881** [CoolPhilChen/SJTU-Courses#12]
数据结构和和高级算法，，，，有中文版的吗？

**Comment by DiamondI** [comment]
**CS221 数据结构**课程是一门中文授课的课程，使用的教材是《数据结构:思想与实现》(翁惠玉, 俞勇)，这是一本中文教材，而且该课程使用的课件也是中文的；但是**EI375 高级算法**这门课，据我所知是一门英文授课的课程，课件也是使用的英文，因此目前没有中文版的资料，但将来也许会上传中文授课的高级算法课程的资料。

**Comment by coderaka** [comment]
高级算法课是中文讲的，但是notes只有英文。这门课的课程材料不大可能也没有必要用中文，因为是老师现写的，英文能让更多人看到。

**Comment by DiamondI** [comment]
这个issue有一段时间没有更新了，现在先关闭这个issue，如果将来有什么关于本issue的其他问题，可以将这个issue重新开启。
