### ISSUE TITLE
数学课程

### ISSUE THREAD

**Issue by igorhuangchao** [CoolPhilChen/SJTU-Courses#2]
非常感谢分享，不知道进一步会不会有更多数学相关的分享，比如高数，代数。 谢谢

**Comment by CoolPhilChen** [comment]
你好, 谢谢你的建议. 我们后面会逐渐完善数学方面的课程.

**Comment by DiamondI** [comment]
这个issue有一段时间没有更新了，现在先暂时关闭本issue，将来如果有出现与本issue相关的问题，可以重新打开这个issue并进一步讨论。
