### ISSUE TITLE
The repository is too large to download easily

### ISSUE THREAD

**Issue by songwonderful** [CoolPhilChen/SJTU-Courses#7]
Expect **Baidu Cloud Disk** download link, thanks.
Anyway, thanks a lot for sharing.
**o(*￣▽￣*)ブ**

**Comment by DiamondI** [comment]
We don't think it's a good idea to use **Baidu Cloud Disk** for the reason that this repo is still updating. Actually, you can download the specific folders using a chrome extension, named [gitzip](https://chrome.google.com/webstore/detail/gitzip-for-github/ffabmkklhbepgcgfonabamgnfafbdlkn/related)(can also be used in opera and firefox), easily. Furthermore, we will update **README** and show how to deal with this large repository with **gitzip**.

Hope that helps!:blush:

**Comment by DiamondI** [comment]
This issue has not been updated over a month, and I will close this issue temporarily. If there's any question related to this issue, please reopen it and discuss further.
